/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account-settings': RouteRecordInfo<
      '/account-settings',
      '/account-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/analytics/': RouteRecordInfo<
      '/analytics/',
      '/analytics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/api-keys/': RouteRecordInfo<
      '/api-keys/',
      '/api-keys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/api-keys/new': RouteRecordInfo<
      '/api-keys/new',
      '/api-keys/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/explore/': RouteRecordInfo<
      '/explore/',
      '/explore',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/explore/by-other-creators': RouteRecordInfo<
      '/explore/by-other-creators',
      '/explore/by-other-creators',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/explore/hytale-plugins': RouteRecordInfo<
      '/explore/hytale-plugins',
      '/explore/hytale-plugins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/explore/minecraft-plugins': RouteRecordInfo<
      '/explore/minecraft-plugins',
      '/explore/minecraft-plugins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/explore/other-projects': RouteRecordInfo<
      '/explore/other-projects',
      '/explore/other-projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/spaces/[sid]/': RouteRecordInfo<
      '/spaces/[sid]/',
      '/spaces/:sid',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/analytics/': RouteRecordInfo<
      '/spaces/[sid]/analytics/',
      '/spaces/:sid/analytics',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/analytics/dashboards/': RouteRecordInfo<
      '/spaces/[sid]/analytics/dashboards/',
      '/spaces/:sid/analytics/dashboards',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/analytics/dashboards/new': RouteRecordInfo<
      '/spaces/[sid]/analytics/dashboards/new',
      '/spaces/:sid/analytics/dashboards/new',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/analytics/metrics': RouteRecordInfo<
      '/spaces/[sid]/analytics/metrics',
      '/spaces/:sid/analytics/metrics',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/blog/': RouteRecordInfo<
      '/spaces/[sid]/blog/',
      '/spaces/:sid/blog',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/blog/[blogid]/': RouteRecordInfo<
      '/spaces/[sid]/blog/[blogid]/',
      '/spaces/:sid/blog/:blogid',
      { sid: ParamValue<true>, blogid: ParamValue<true> },
      { sid: ParamValue<false>, blogid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/blog/[blogid]/edit': RouteRecordInfo<
      '/spaces/[sid]/blog/[blogid]/edit',
      '/spaces/:sid/blog/:blogid/edit',
      { sid: ParamValue<true>, blogid: ParamValue<true> },
      { sid: ParamValue<false>, blogid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/blog/new': RouteRecordInfo<
      '/spaces/[sid]/blog/new',
      '/spaces/:sid/blog/new',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/features': RouteRecordInfo<
      '/spaces/[sid]/features',
      '/spaces/:sid/features',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/issues/': RouteRecordInfo<
      '/spaces/[sid]/issues/',
      '/spaces/:sid/issues',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/issues/[iid]/': RouteRecordInfo<
      '/spaces/[sid]/issues/[iid]/',
      '/spaces/:sid/issues/:iid',
      { sid: ParamValue<true>, iid: ParamValue<true> },
      { sid: ParamValue<false>, iid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/issues/[iid]/edit': RouteRecordInfo<
      '/spaces/[sid]/issues/[iid]/edit',
      '/spaces/:sid/issues/:iid/edit',
      { sid: ParamValue<true>, iid: ParamValue<true> },
      { sid: ParamValue<false>, iid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/issues/new': RouteRecordInfo<
      '/spaces/[sid]/issues/new',
      '/spaces/:sid/issues/new',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/javadoc/': RouteRecordInfo<
      '/spaces/[sid]/javadoc/',
      '/spaces/:sid/javadoc',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/maven-repos/': RouteRecordInfo<
      '/spaces/[sid]/maven-repos/',
      '/spaces/:sid/maven-repos',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/maven-repos/[mvrid]/': RouteRecordInfo<
      '/spaces/[sid]/maven-repos/[mvrid]/',
      '/spaces/:sid/maven-repos/:mvrid',
      { sid: ParamValue<true>, mvrid: ParamValue<true> },
      { sid: ParamValue<false>, mvrid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/maven-repos/[mvrid]/[mvaid]/': RouteRecordInfo<
      '/spaces/[sid]/maven-repos/[mvrid]/[mvaid]/',
      '/spaces/:sid/maven-repos/:mvrid/:mvaid',
      { sid: ParamValue<true>, mvrid: ParamValue<true>, mvaid: ParamValue<true> },
      { sid: ParamValue<false>, mvrid: ParamValue<false>, mvaid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/secrets/': RouteRecordInfo<
      '/spaces/[sid]/secrets/',
      '/spaces/:sid/secrets',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/secrets/[secretid]/': RouteRecordInfo<
      '/spaces/[sid]/secrets/[secretid]/',
      '/spaces/:sid/secrets/:secretid',
      { sid: ParamValue<true>, secretid: ParamValue<true> },
      { sid: ParamValue<false>, secretid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/secrets/new': RouteRecordInfo<
      '/spaces/[sid]/secrets/new',
      '/spaces/:sid/secrets/new',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/settings': RouteRecordInfo<
      '/spaces/[sid]/settings',
      '/spaces/:sid/settings',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/storage/': RouteRecordInfo<
      '/spaces/[sid]/storage/',
      '/spaces/:sid/storage',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/storage/[dbid]/': RouteRecordInfo<
      '/spaces/[sid]/storage/[dbid]/',
      '/spaces/:sid/storage/:dbid',
      { sid: ParamValue<true>, dbid: ParamValue<true> },
      { sid: ParamValue<false>, dbid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/storage/[dbid]/[collid]/': RouteRecordInfo<
      '/spaces/[sid]/storage/[dbid]/[collid]/',
      '/spaces/:sid/storage/:dbid/:collid',
      { sid: ParamValue<true>, dbid: ParamValue<true>, collid: ParamValue<true> },
      { sid: ParamValue<false>, dbid: ParamValue<false>, collid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/versions/': RouteRecordInfo<
      '/spaces/[sid]/versions/',
      '/spaces/:sid/versions',
      { sid: ParamValue<true> },
      { sid: ParamValue<false> },
      | never
    >,
    '/spaces/[sid]/versions/[vid]/': RouteRecordInfo<
      '/spaces/[sid]/versions/[vid]/',
      '/spaces/:sid/versions/:vid',
      { sid: ParamValue<true>, vid: ParamValue<true> },
      { sid: ParamValue<false>, vid: ParamValue<false> },
      | never
    >,
    '/spaces/new': RouteRecordInfo<
      '/spaces/new',
      '/spaces/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/java-sdk': RouteRecordInfo<
      '/tools/java-sdk',
      '/tools/java-sdk',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/markdown-editor': RouteRecordInfo<
      '/tools/markdown-editor',
      '/tools/markdown-editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/[userid]/': RouteRecordInfo<
      '/users/[userid]/',
      '/users/:userid',
      { userid: ParamValue<true> },
      { userid: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/account-settings.vue': {
      routes:
        | '/account-settings'
      views:
        | never
    }
    'src/pages/analytics/index.vue': {
      routes:
        | '/analytics/'
      views:
        | never
    }
    'src/pages/api-keys/index.vue': {
      routes:
        | '/api-keys/'
      views:
        | never
    }
    'src/pages/api-keys/new.vue': {
      routes:
        | '/api-keys/new'
      views:
        | never
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
    }
    'src/pages/explore/index.vue': {
      routes:
        | '/explore/'
      views:
        | never
    }
    'src/pages/explore/by-other-creators.vue': {
      routes:
        | '/explore/by-other-creators'
      views:
        | never
    }
    'src/pages/explore/hytale-plugins.vue': {
      routes:
        | '/explore/hytale-plugins'
      views:
        | never
    }
    'src/pages/explore/minecraft-plugins.vue': {
      routes:
        | '/explore/minecraft-plugins'
      views:
        | never
    }
    'src/pages/explore/other-projects.vue': {
      routes:
        | '/explore/other-projects'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
    }
    'src/pages/spaces/[sid]/index.vue': {
      routes:
        | '/spaces/[sid]/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/analytics/index.vue': {
      routes:
        | '/spaces/[sid]/analytics/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/analytics/dashboards/index.vue': {
      routes:
        | '/spaces/[sid]/analytics/dashboards/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/analytics/dashboards/new.vue': {
      routes:
        | '/spaces/[sid]/analytics/dashboards/new'
      views:
        | never
    }
    'src/pages/spaces/[sid]/analytics/metrics.vue': {
      routes:
        | '/spaces/[sid]/analytics/metrics'
      views:
        | never
    }
    'src/pages/spaces/[sid]/blog/index.vue': {
      routes:
        | '/spaces/[sid]/blog/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/blog/[blogid]/index.vue': {
      routes:
        | '/spaces/[sid]/blog/[blogid]/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/blog/[blogid]/edit.vue': {
      routes:
        | '/spaces/[sid]/blog/[blogid]/edit'
      views:
        | never
    }
    'src/pages/spaces/[sid]/blog/new.vue': {
      routes:
        | '/spaces/[sid]/blog/new'
      views:
        | never
    }
    'src/pages/spaces/[sid]/features.vue': {
      routes:
        | '/spaces/[sid]/features'
      views:
        | never
    }
    'src/pages/spaces/[sid]/issues/index.vue': {
      routes:
        | '/spaces/[sid]/issues/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/issues/[iid]/index.vue': {
      routes:
        | '/spaces/[sid]/issues/[iid]/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/issues/[iid]/edit.vue': {
      routes:
        | '/spaces/[sid]/issues/[iid]/edit'
      views:
        | never
    }
    'src/pages/spaces/[sid]/issues/new.vue': {
      routes:
        | '/spaces/[sid]/issues/new'
      views:
        | never
    }
    'src/pages/spaces/[sid]/javadoc/index.vue': {
      routes:
        | '/spaces/[sid]/javadoc/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/maven-repos/index.vue': {
      routes:
        | '/spaces/[sid]/maven-repos/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/maven-repos/[mvrid]/index.vue': {
      routes:
        | '/spaces/[sid]/maven-repos/[mvrid]/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/maven-repos/[mvrid]/[mvaid]/index.vue': {
      routes:
        | '/spaces/[sid]/maven-repos/[mvrid]/[mvaid]/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/secrets/index.vue': {
      routes:
        | '/spaces/[sid]/secrets/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/secrets/[secretid]/index.vue': {
      routes:
        | '/spaces/[sid]/secrets/[secretid]/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/secrets/new.vue': {
      routes:
        | '/spaces/[sid]/secrets/new'
      views:
        | never
    }
    'src/pages/spaces/[sid]/settings.vue': {
      routes:
        | '/spaces/[sid]/settings'
      views:
        | never
    }
    'src/pages/spaces/[sid]/storage/index.vue': {
      routes:
        | '/spaces/[sid]/storage/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/storage/[dbid]/index.vue': {
      routes:
        | '/spaces/[sid]/storage/[dbid]/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/storage/[dbid]/[collid]/index.vue': {
      routes:
        | '/spaces/[sid]/storage/[dbid]/[collid]/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/versions/index.vue': {
      routes:
        | '/spaces/[sid]/versions/'
      views:
        | never
    }
    'src/pages/spaces/[sid]/versions/[vid]/index.vue': {
      routes:
        | '/spaces/[sid]/versions/[vid]/'
      views:
        | never
    }
    'src/pages/spaces/new.vue': {
      routes:
        | '/spaces/new'
      views:
        | never
    }
    'src/pages/tools/java-sdk.vue': {
      routes:
        | '/tools/java-sdk'
      views:
        | never
    }
    'src/pages/tools/markdown-editor.vue': {
      routes:
        | '/tools/markdown-editor'
      views:
        | never
    }
    'src/pages/users/[userid]/index.vue': {
      routes:
        | '/users/[userid]/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
