/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/explore/': RouteRecordInfo<'/explore/', '/explore', Record<never, never>, Record<never, never>>,
    '/explore/by-other-creators': RouteRecordInfo<'/explore/by-other-creators', '/explore/by-other-creators', Record<never, never>, Record<never, never>>,
    '/explore/hytale-plugins': RouteRecordInfo<'/explore/hytale-plugins', '/explore/hytale-plugins', Record<never, never>, Record<never, never>>,
    '/explore/minecraft-plugins': RouteRecordInfo<'/explore/minecraft-plugins', '/explore/minecraft-plugins', Record<never, never>, Record<never, never>>,
    '/explore/other-projects': RouteRecordInfo<'/explore/other-projects', '/explore/other-projects', Record<never, never>, Record<never, never>>,
    '/spaces/[sid]/': RouteRecordInfo<'/spaces/[sid]/', '/spaces/:sid', { sid: ParamValue<true> }, { sid: ParamValue<false> }>,
    '/spaces/[sid]/issues/': RouteRecordInfo<'/spaces/[sid]/issues/', '/spaces/:sid/issues', { sid: ParamValue<true> }, { sid: ParamValue<false> }>,
    '/spaces/[sid]/issues/[iid]/': RouteRecordInfo<'/spaces/[sid]/issues/[iid]/', '/spaces/:sid/issues/:iid', { sid: ParamValue<true>, iid: ParamValue<true> }, { sid: ParamValue<false>, iid: ParamValue<false> }>,
    '/spaces/[sid]/issues/new': RouteRecordInfo<'/spaces/[sid]/issues/new', '/spaces/:sid/issues/new', { sid: ParamValue<true> }, { sid: ParamValue<false> }>,
    '/spaces/[sid]/versions/': RouteRecordInfo<'/spaces/[sid]/versions/', '/spaces/:sid/versions', { sid: ParamValue<true> }, { sid: ParamValue<false> }>,
    '/spaces/[sid]/versions/[vid]/': RouteRecordInfo<'/spaces/[sid]/versions/[vid]/', '/spaces/:sid/versions/:vid', { sid: ParamValue<true>, vid: ParamValue<true> }, { sid: ParamValue<false>, vid: ParamValue<false> }>,
    '/tools/java-sdk': RouteRecordInfo<'/tools/java-sdk', '/tools/java-sdk', Record<never, never>, Record<never, never>>,
    '/tools/markdown-editor': RouteRecordInfo<'/tools/markdown-editor', '/tools/markdown-editor', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/auth/login.vue': {
      routes: '/auth/login'
      views: never
    }
    'src/pages/explore/index.vue': {
      routes: '/explore/'
      views: never
    }
    'src/pages/explore/by-other-creators.vue': {
      routes: '/explore/by-other-creators'
      views: never
    }
    'src/pages/explore/hytale-plugins.vue': {
      routes: '/explore/hytale-plugins'
      views: never
    }
    'src/pages/explore/minecraft-plugins.vue': {
      routes: '/explore/minecraft-plugins'
      views: never
    }
    'src/pages/explore/other-projects.vue': {
      routes: '/explore/other-projects'
      views: never
    }
    'src/pages/spaces/[sid]/index.vue': {
      routes: '/spaces/[sid]/'
      views: never
    }
    'src/pages/spaces/[sid]/issues/index.vue': {
      routes: '/spaces/[sid]/issues/'
      views: never
    }
    'src/pages/spaces/[sid]/issues/[iid]/index.vue': {
      routes: '/spaces/[sid]/issues/[iid]/'
      views: never
    }
    'src/pages/spaces/[sid]/issues/new.vue': {
      routes: '/spaces/[sid]/issues/new'
      views: never
    }
    'src/pages/spaces/[sid]/versions/index.vue': {
      routes: '/spaces/[sid]/versions/'
      views: never
    }
    'src/pages/spaces/[sid]/versions/[vid]/index.vue': {
      routes: '/spaces/[sid]/versions/[vid]/'
      views: never
    }
    'src/pages/tools/java-sdk.vue': {
      routes: '/tools/java-sdk'
      views: never
    }
    'src/pages/tools/markdown-editor.vue': {
      routes: '/tools/markdown-editor'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
